# Generated by Django 4.1.4 on 2022-12-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoterRecord',
            fields=[
                ('identity_number', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('block_code', models.CharField(max_length=200)),
                ('polling_station', models.CharField(max_length=200)),
                ('polling_booth', models.CharField(max_length=200)),
            ],
        ),
    ]
